// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// video_doom //
// ---------- //

#define video_doom_wrap_target 0
#define video_doom_wrap 0

#define video_doom_offset_end_of_scanline_skip_ALIGN 0u
#define video_doom_offset_end_of_scanline_ALIGN 0u
#define video_doom_offset_entry_point 0u
#define video_doom_offset_nop_raw 0u
#define video_doom_offset_raw_run 0u
#define video_doom_offset_raw_1p 0u
#define video_doom_offset_raw_run_half 0u
#define video_doom_offset_raw_1p_half 0u
#define video_doom_offset_color_run 0u

static const uint16_t video_doom_program_instructions[] = {
};

#if !PICO_NO_HARDWARE
static const struct pio_program video_doom_program = {
    .instructions = video_doom_program_instructions,
    .length = 0,
    .origin = 0,
};

static inline pio_sm_config video_doom_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + video_doom_wrap_target, offset + video_doom_wrap);
    return c;
}
#endif

